### ISSUE TITLE
TypeError: UpgradeThread.percentSignal [object, object, object] signal has 3 argument (s) but 1 provided

### ISSUE THREAD

**Issue by laurapala** [DFRobot/Bluno2_Firmware#1]
Hello,
I upgraded the firmware of FireBeetle Board-328P with BLE4.1, but at the end of the process I get this message:

"Exception in Thread-1 thread:
Traceback (most recent call last):
   File "threading.pyo", line 801, in __bootstrap_inner
   File "bluno2v0.3.py", line 234, in run
TypeError: UpgradeThread.percentSignal [object, object, object] signal has 3 argument (s) but 1 provided"

What does it mean?
Thank you

**Comment by BlackHeart-TF** [comment]
im getting this now too, its likely something to do with the version of python its using, but havent found a fix yet
